# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-CybozuOffice6
version:      0.03
version_from: lib/WWW/CybozuOffice6.pm
installdirs:  site
requires:
    Carp:                          0
    Jcode:                         0
    LWP:                           0
    Text::CSV_XS:                  0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
